// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: internal/proto/siem.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_internal_proto_siem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_siem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_internal_proto_siem_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_internal_proto_siem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_siem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_internal_proto_siem_proto_rawDescGZIP(), []int{1}
}

func (x *Alert) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Alert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Area          string                 `protobuf:"bytes,2,opt,name=area,proto3" json:"area,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_internal_proto_siem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_siem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_internal_proto_siem_proto_rawDescGZIP(), []int{2}
}

func (x *Log) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Log) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

type UserID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserID) Reset() {
	*x = UserID{}
	mi := &file_internal_proto_siem_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_siem_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_internal_proto_siem_proto_rawDescGZIP(), []int{3}
}

func (x *UserID) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AlertID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertID) Reset() {
	*x = AlertID{}
	mi := &file_internal_proto_siem_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertID) ProtoMessage() {}

func (x *AlertID) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_siem_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertID.ProtoReflect.Descriptor instead.
func (*AlertID) Descriptor() ([]byte, []int) {
	return file_internal_proto_siem_proto_rawDescGZIP(), []int{4}
}

func (x *AlertID) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LogID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogID) Reset() {
	*x = LogID{}
	mi := &file_internal_proto_siem_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogID) ProtoMessage() {}

func (x *LogID) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_siem_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogID.ProtoReflect.Descriptor instead.
func (*LogID) Descriptor() ([]byte, []int) {
	return file_internal_proto_siem_proto_rawDescGZIP(), []int{5}
}

func (x *LogID) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_proto_siem_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_siem_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_proto_siem_proto_rawDescGZIP(), []int{6}
}

type UserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserList) Reset() {
	*x = UserList{}
	mi := &file_internal_proto_siem_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserList) ProtoMessage() {}

func (x *UserList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_siem_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserList.ProtoReflect.Descriptor instead.
func (*UserList) Descriptor() ([]byte, []int) {
	return file_internal_proto_siem_proto_rawDescGZIP(), []int{7}
}

func (x *UserList) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type AlertList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*Alert               `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertList) Reset() {
	*x = AlertList{}
	mi := &file_internal_proto_siem_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertList) ProtoMessage() {}

func (x *AlertList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_siem_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertList.ProtoReflect.Descriptor instead.
func (*AlertList) Descriptor() ([]byte, []int) {
	return file_internal_proto_siem_proto_rawDescGZIP(), []int{8}
}

func (x *AlertList) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

type LogList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*Log                 `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogList) Reset() {
	*x = LogList{}
	mi := &file_internal_proto_siem_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogList) ProtoMessage() {}

func (x *LogList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_siem_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogList.ProtoReflect.Descriptor instead.
func (*LogList) Descriptor() ([]byte, []int) {
	return file_internal_proto_siem_proto_rawDescGZIP(), []int{9}
}

func (x *LogList) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

var File_internal_proto_siem_proto protoreflect.FileDescriptor

const file_internal_proto_siem_proto_rawDesc = "" +
	"\n" +
	"\x19internal/proto/siem.proto\x12\x04siem\",\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\"1\n" +
	"\x05Alert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\")\n" +
	"\x03Log\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04area\x18\x02 \x01(\tR\x04area\"\x18\n" +
	"\x06UserID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x19\n" +
	"\aAlertID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x17\n" +
	"\x05LogID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\a\n" +
	"\x05Empty\",\n" +
	"\bUserList\x12 \n" +
	"\x05users\x18\x01 \x03(\v2\n" +
	".siem.UserR\x05users\"0\n" +
	"\tAlertList\x12#\n" +
	"\x06alerts\x18\x01 \x03(\v2\v.siem.AlertR\x06alerts\"(\n" +
	"\aLogList\x12\x1d\n" +
	"\x04logs\x18\x01 \x03(\v2\t.siem.LogR\x04logs2\xd1\x01\n" +
	"\vUserService\x12$\n" +
	"\n" +
	"CreateUser\x12\n" +
	".siem.User\x1a\n" +
	".siem.User\x12#\n" +
	"\aGetUser\x12\f.siem.UserID\x1a\n" +
	".siem.User\x12$\n" +
	"\n" +
	"UpdateUser\x12\n" +
	".siem.User\x1a\n" +
	".siem.User\x12'\n" +
	"\n" +
	"DeleteUser\x12\f.siem.UserID\x1a\v.siem.Empty\x12(\n" +
	"\tListUsers\x12\v.siem.Empty\x1a\x0e.siem.UserList2\xdf\x01\n" +
	"\fAlertService\x12'\n" +
	"\vCreateAlert\x12\v.siem.Alert\x1a\v.siem.Alert\x12&\n" +
	"\bGetAlert\x12\r.siem.AlertID\x1a\v.siem.Alert\x12'\n" +
	"\vUpdateAlert\x12\v.siem.Alert\x1a\v.siem.Alert\x12)\n" +
	"\vDeleteAlert\x12\r.siem.AlertID\x1a\v.siem.Empty\x12*\n" +
	"\n" +
	"ListAlerts\x12\v.siem.Empty\x1a\x0f.siem.AlertList2\xc3\x01\n" +
	"\n" +
	"LogService\x12!\n" +
	"\tCreateLog\x12\t.siem.Log\x1a\t.siem.Log\x12 \n" +
	"\x06GetLog\x12\v.siem.LogID\x1a\t.siem.Log\x12!\n" +
	"\tUpdateLog\x12\t.siem.Log\x1a\t.siem.Log\x12%\n" +
	"\tDeleteLog\x12\v.siem.LogID\x1a\v.siem.Empty\x12&\n" +
	"\bListLogs\x12\v.siem.Empty\x1a\r.siem.LogListB\x16Z\x14internal/proto/pb;pbb\x06proto3"

var (
	file_internal_proto_siem_proto_rawDescOnce sync.Once
	file_internal_proto_siem_proto_rawDescData []byte
)

func file_internal_proto_siem_proto_rawDescGZIP() []byte {
	file_internal_proto_siem_proto_rawDescOnce.Do(func() {
		file_internal_proto_siem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_siem_proto_rawDesc), len(file_internal_proto_siem_proto_rawDesc)))
	})
	return file_internal_proto_siem_proto_rawDescData
}

var file_internal_proto_siem_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_proto_siem_proto_goTypes = []any{
	(*User)(nil),      // 0: siem.User
	(*Alert)(nil),     // 1: siem.Alert
	(*Log)(nil),       // 2: siem.Log
	(*UserID)(nil),    // 3: siem.UserID
	(*AlertID)(nil),   // 4: siem.AlertID
	(*LogID)(nil),     // 5: siem.LogID
	(*Empty)(nil),     // 6: siem.Empty
	(*UserList)(nil),  // 7: siem.UserList
	(*AlertList)(nil), // 8: siem.AlertList
	(*LogList)(nil),   // 9: siem.LogList
}
var file_internal_proto_siem_proto_depIdxs = []int32{
	0,  // 0: siem.UserList.users:type_name -> siem.User
	1,  // 1: siem.AlertList.alerts:type_name -> siem.Alert
	2,  // 2: siem.LogList.logs:type_name -> siem.Log
	0,  // 3: siem.UserService.CreateUser:input_type -> siem.User
	3,  // 4: siem.UserService.GetUser:input_type -> siem.UserID
	0,  // 5: siem.UserService.UpdateUser:input_type -> siem.User
	3,  // 6: siem.UserService.DeleteUser:input_type -> siem.UserID
	6,  // 7: siem.UserService.ListUsers:input_type -> siem.Empty
	1,  // 8: siem.AlertService.CreateAlert:input_type -> siem.Alert
	4,  // 9: siem.AlertService.GetAlert:input_type -> siem.AlertID
	1,  // 10: siem.AlertService.UpdateAlert:input_type -> siem.Alert
	4,  // 11: siem.AlertService.DeleteAlert:input_type -> siem.AlertID
	6,  // 12: siem.AlertService.ListAlerts:input_type -> siem.Empty
	2,  // 13: siem.LogService.CreateLog:input_type -> siem.Log
	5,  // 14: siem.LogService.GetLog:input_type -> siem.LogID
	2,  // 15: siem.LogService.UpdateLog:input_type -> siem.Log
	5,  // 16: siem.LogService.DeleteLog:input_type -> siem.LogID
	6,  // 17: siem.LogService.ListLogs:input_type -> siem.Empty
	0,  // 18: siem.UserService.CreateUser:output_type -> siem.User
	0,  // 19: siem.UserService.GetUser:output_type -> siem.User
	0,  // 20: siem.UserService.UpdateUser:output_type -> siem.User
	6,  // 21: siem.UserService.DeleteUser:output_type -> siem.Empty
	7,  // 22: siem.UserService.ListUsers:output_type -> siem.UserList
	1,  // 23: siem.AlertService.CreateAlert:output_type -> siem.Alert
	1,  // 24: siem.AlertService.GetAlert:output_type -> siem.Alert
	1,  // 25: siem.AlertService.UpdateAlert:output_type -> siem.Alert
	6,  // 26: siem.AlertService.DeleteAlert:output_type -> siem.Empty
	8,  // 27: siem.AlertService.ListAlerts:output_type -> siem.AlertList
	2,  // 28: siem.LogService.CreateLog:output_type -> siem.Log
	2,  // 29: siem.LogService.GetLog:output_type -> siem.Log
	2,  // 30: siem.LogService.UpdateLog:output_type -> siem.Log
	6,  // 31: siem.LogService.DeleteLog:output_type -> siem.Empty
	9,  // 32: siem.LogService.ListLogs:output_type -> siem.LogList
	18, // [18:33] is the sub-list for method output_type
	3,  // [3:18] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_proto_siem_proto_init() }
func file_internal_proto_siem_proto_init() {
	if File_internal_proto_siem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_siem_proto_rawDesc), len(file_internal_proto_siem_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_internal_proto_siem_proto_goTypes,
		DependencyIndexes: file_internal_proto_siem_proto_depIdxs,
		MessageInfos:      file_internal_proto_siem_proto_msgTypes,
	}.Build()
	File_internal_proto_siem_proto = out.File
	file_internal_proto_siem_proto_goTypes = nil
	file_internal_proto_siem_proto_depIdxs = nil
}
